FROM docker.elastic.co/beats/filebeat:7.5.1
COPY filebeat.yml /usr/share/filebeat/filebeat.yml
USER root
RUN mkdir /usr/share/filebeat/logdata
RUN chown root:filebeat /usr/share/filebeat/filebeat.yml
USER filebeat