FROM logstash:7.5.1
USER root
RUN mkdir /usr/share/logstash/logdata
RUN chown -R logstash:logstash /usr/share/logstash/logdata
RUN rm -f /usr/share/logstash/pipeline/logstash.conf
COPY --chown=logstash:logstash ./pipeline/logstash.conf /usr/share/logstash/pipeline/
RUN rm -f /usr/share/logstash/config/logstash.yml
COPY --chown=logstash:logstash ./config/logstash.yml /usr/share/logstash/config/
USER logstash